insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Emard Inc', 'FGOKVN', 'Walton', '7214', '5856', 'Embalse');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Olson, Predovic and Conn', 'MVABCD', 'Glendale', '44236', null, 'Sangallaya');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Kihn-Heidenreich', 'RYFTNG', 'Eastlawn', '00324', null, 'Tunjë');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Quigley Group', 'TGIATC', 'Norway Maple', '601', null, 'Maliq');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Grimes LLC', 'RJKTCW', 'Ilene', '8248', '7947', 'Pleasant Point');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Lueilwitz-Gerhold', 'TIVYUI', 'Scott', '093', '5001', 'Balabag');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Hauck LLC', 'UCCUDF', 'Crownhardt', '793', null, 'Tlumach');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('O''Connell-Dooley', 'ZJYIMV', 'Cherokee', '6', null, 'Lianshi');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Pagac, Schaden and Jones', 'PAZGCS', 'Cambridge', '23', '4207', 'San Nicolas');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Koss, Blick and Abshire', 'ISGRDD', 'Crest Line', '2', null, 'Makueni');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('McKenzie-Franecki', 'MTBRVC', 'Pawling', '68385', null, 'Gununggoong');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('O''Hara and Sons', 'HCKNOP', 'Arrowood', '2', null, 'Baisha');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Mueller, Yost and O''Kon', 'EMCTAC', 'Marcy', '68', '8407', 'Manat');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Stracke Inc', 'UZVUUQ', 'Hagan', '26763', '35740-000', 'Esmeraldas');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('O''Kon Inc', 'IUGSZH', 'Esker', '2492', null, 'Xiaosong');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Jacobi, Veum and Labadie', 'QDLAXM', 'Monument', '555', null, 'Yonghe');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Prohaska-Legros', 'DVEYFM', 'Towne', '22477', null, 'Wujiao');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Keebler-Flatley', 'QCHVXE', 'Cody', '67890', '999-8524', 'Tomioka');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('McGlynn-VonRueden', 'DGIZLW', 'Nobel', '88', '397815', 'Devitsa');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Macejkovic, Kessler and Okuneva', 'BSFZHM', 'Stephen', '2', null, 'Zhuli');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Legros, Thiel and Terry', 'JQLVNO', 'Warrior', '35', '2718', 'Cervantes');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Larson, O''Hara and Pacocha', 'JYELVS', 'Grim', '97', null, 'Basqal');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Gibson-Friesen', 'XSTMOM', 'Jana', '84204', null, 'Tân Hưng');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Cronin-Daniel', 'MGBSBF', 'Gateway', '994', null, 'Caihe');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Klein, Mills and Morissette', 'MKANYL', 'Fremont', '669', '72130', 'Sam Chuk');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Gorczany-Jacobs', 'VOHGAP', 'Summer Ridge', '924', null, 'Tangjia');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Hettinger-Moore', 'ASIBKS', 'Brown', '67', '99-200', 'Poddębice');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Mitchell-Huels', 'CAHYAG', 'Rowland', '96', null, 'Aserrío de Gariché');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Tillman-Durgan', 'AKEDKM', 'Oneill', '7514', '368551', 'Kizilyurt');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Hills-Harber', 'VCGHQK', 'Gulseth', '373', '658741', 'Shipunovo');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Rohan-Barton', 'DQPHRL', 'Haas', '7', null, 'Daxi');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Metz-Prosacco', 'SZWFLP', 'David', '66', null, 'Guanyao');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Breitenberg, Kovacek and Rice', 'PEYAJP', 'Old Shore', '78', '0748', 'North Shore');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Baumbach, Fritsch and D''Amore', 'PYYSWT', 'Mariners Cove', '98133', '6121', 'Huanchillas');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Gerlach, Reinger and Muller', 'FHKNOQ', 'Eagan', '09594', null, 'Cocobeach');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Herzog-Mayert', 'AIRKVW', 'Kinsman', '40', null, 'Changshou');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Kemmer-Crona', 'PWVKAL', 'Sugar', '0', null, 'Xankandi');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Greenfelder, Fadel and Stanton', 'OLWKFY', 'Gateway', '8198', null, 'Dabai');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Metz Inc', 'ZIGYHT', 'Eagle Crest', '79919', null, 'Huangyang');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Walter-Breitenberg', 'EVMELH', 'Dawn', '5', null, 'Sarirejo Satu');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Veum-Robel', 'EJDPNE', 'Kings', '927', '76926 CEDEX 9', 'Rouen');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Jones Group', 'CYZZYD', 'Knutson', '2033', null, 'Vohipaho');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Johnston-Hermiston', 'RAEXIK', 'Beilfuss', '0', '75863 CEDEX 18', 'Paris 18');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Crist, Gorczany and Cartwright', 'LDFZLM', 'Hallows', '4982', null, 'Kuilehe');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Homenick Group', 'WVVCHA', 'Banding', '6', '38740-000', 'Patrocínio');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Stehr-Schultz', 'DRHIBM', 'Schiller', '25523', '4580-604', 'Sobrosa');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Farrell and Sons', 'UPOIEH', 'Talisman', '715', null, 'Chenxiang');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Connelly and Sons', 'IZPFKZ', 'Ruskin', '8', '58300-000', 'Santa Rita');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Baumbach, Streich and Olson', 'MWRNPE', 'North', '1', '10702', 'San Cristóbal');
insert into organization (organization_name, organization_abbreviation, street, streetno, postalcode, city) values ('Schaefer, Fahey and McKenzie', 'EKDEMN', 'Brentwood', '12', null, 'Tārūt');
