insert into project_scientific_field (project_title, scientific_field_name) values ('Gwxxoevdl', 'care one sore throat');
insert into project_scientific_field (project_title, scientific_field_name) values ('Tfyrlitma', 'HairQ-Plus');
insert into project_scientific_field (project_title, scientific_field_name) values ('Bpqrtffwq', 'Levetiracetam');
insert into project_scientific_field (project_title, scientific_field_name) values ('Kjiqweyse', 'Gabapentin');
insert into project_scientific_field (project_title, scientific_field_name) values ('Ldtsgmosf', 'Fluocinolone Acetonide');
insert into project_scientific_field (project_title, scientific_field_name) values ('Lejyysrar', 'Carbidopa and Levodopa');
insert into project_scientific_field (project_title, scientific_field_name) values ('Bzhctbzii', 'Quetiapine Fumarate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Hotfcjyds', 'benzonatate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Hfunzwwdg', 'Amlodipine Besylate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Pvyzmyqbq', 'Tag Alder');
insert into project_scientific_field (project_title, scientific_field_name) values ('Ktvezedqw', 'Tag Alder');
insert into project_scientific_field (project_title, scientific_field_name) values ('Afyfvsfdh', 'HairQ-Plus');
insert into project_scientific_field (project_title, scientific_field_name) values ('Jnutsxvxp', 'Fluocinolone Acetonide');
insert into project_scientific_field (project_title, scientific_field_name) values ('Wpnuhcvnh', 'Carbidopa and Levodopa');
insert into project_scientific_field (project_title, scientific_field_name) values ('Iuubyhtet', 'Gabapentin');
insert into project_scientific_field (project_title, scientific_field_name) values ('Flsppzchu', 'Amlodipine Besylate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Utmuwitnn', 'benzonatate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Oqvdflgkk', 'Quetiapine Fumarate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Mhkmkvnlm', 'care one sore throat');
insert into project_scientific_field (project_title, scientific_field_name) values ('Vknkwhvev', 'Levetiracetam');
insert into project_scientific_field (project_title, scientific_field_name) values ('Ojnvaebtr', 'benzonatate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Emwstxhlh', 'care one sore throat');
insert into project_scientific_field (project_title, scientific_field_name) values ('Rtoixcclv', 'Quetiapine Fumarate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Nizwyjeuy', 'Carbidopa and Levodopa');
insert into project_scientific_field (project_title, scientific_field_name) values ('Qezlleliu', 'Amlodipine Besylate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Fuwantahl', 'HairQ-Plus');
insert into project_scientific_field (project_title, scientific_field_name) values ('Beasvvqgf', 'Fluocinolone Acetonide');
insert into project_scientific_field (project_title, scientific_field_name) values ('Anvngeidu', 'Gabapentin');
insert into project_scientific_field (project_title, scientific_field_name) values ('Jwqmhjzuo', 'Levetiracetam');
insert into project_scientific_field (project_title, scientific_field_name) values ('Ycwcphetv', 'Tag Alder');
insert into project_scientific_field (project_title, scientific_field_name) values ('Lrynwhgje', 'care one sore throat');
insert into project_scientific_field (project_title, scientific_field_name) values ('Ijcelqvup', 'HairQ-Plus');
insert into project_scientific_field (project_title, scientific_field_name) values ('Urmhldqfs', 'Carbidopa and Levodopa');
insert into project_scientific_field (project_title, scientific_field_name) values ('Pfsrqhihe', 'Quetiapine Fumarate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Cxbyjjmym', 'Fluocinolone Acetonide');
insert into project_scientific_field (project_title, scientific_field_name) values ('Mpaxtkgvh', 'Gabapentin');
insert into project_scientific_field (project_title, scientific_field_name) values ('Scphslbep', 'Tag Alder');
insert into project_scientific_field (project_title, scientific_field_name) values ('Fvjsdafig', 'benzonatate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Cieuxwyun', 'Levetiracetam');
insert into project_scientific_field (project_title, scientific_field_name) values ('Qbvzueqdg', 'Amlodipine Besylate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Spqurxqfh', 'HairQ-Plus');
insert into project_scientific_field (project_title, scientific_field_name) values ('Dtblslnln', 'Quetiapine Fumarate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Fnpkjoejs', 'Fluocinolone Acetonide');
insert into project_scientific_field (project_title, scientific_field_name) values ('Bajzlifcr', 'care one sore throat');
insert into project_scientific_field (project_title, scientific_field_name) values ('Glyzvyqxm', 'benzonatate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Nerlpuxcu', 'Tag Alder');
insert into project_scientific_field (project_title, scientific_field_name) values ('Zmlcqljqb', 'Amlodipine Besylate');
insert into project_scientific_field (project_title, scientific_field_name) values ('Ltsbxbgcn', 'Carbidopa and Levodopa');
insert into project_scientific_field (project_title, scientific_field_name) values ('Kgmbyfgny', 'Levetiracetam');
insert into project_scientific_field (project_title, scientific_field_name) values ('Ufojgvngc', 'Gabapentin');
